server {
    listen 80;
    server_name parodia.dev;

    # Matrix delegation. Files live at /usr/share/nginx/html/.well-known/matrix/{server,client}
    location /.well-known/matrix/ {
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        root /usr/share/nginx/html;
    }
}
